site_name: Grasshopper

repo_name: "2022.2-Grasshopper"
repo_url: "https://github.com/Requisitos-de-Software/2022.2-Grasshopper"

theme:
  name: material
  language: "pt"
  logo: assets/grasshopper.svg
  favicon: assets/fav.png
  palette:
    primary: indigo
    accent: light green
  features:
    - navigation.tabs

nav:
  - Inicio: index.md
  - Planejamento:
      - Reuniões: planejamento/reunioes.md
      - Metodologia: planejamento/metodologia.md
      - Ferramentas: planejamento/ferramentas.md
      - Cronograma: planejamento/cronograma.md
      - Aplicativos analisados: planejamento/aplicativos-analisados.md
  - Pré-Rastreabilidade:
      - Rich Picture: pre-traceability/richpicture.md
  - Elicitação:
      - Perfil do usuário: elicitacao/perfil-do-usuario.md
      - Personas: elicitacao/personas.md
      - Storytelling: elicitacao/storytelling.md
      - Brainstorm: elicitacao/brainstorm.md
      - Observação: elicitacao/observacao.md
      - Priorização:
          - In or Out: elicitacao/priorizacao/in-or-out.md
          - Three Level-Scale: elicitacao/priorizacao/threeLevel-Scale.md
  - Modelagem:
      - Cenários: modelagem/cenarios.md
      - Léxicos: modelagem/lexicos.md
      - Casos de Uso: modelagem/casos-de-uso.md
      - Especifição Suplementar: modelagem/especificao-suplementar.md
      - Ágil:
          - Backlog: modelagem/modelagemAgil/backlog.md
          - Histórias de Usuário: modelagem/modelagemAgil/historias-de-usuario.md
          - NFR Framework: modelagem/modelagemAgil/nfr-framework.md
  - Análise de Requisitos:
      - Verificação:
          - Modelo Padrão: analise-de-requisitos/verificacao/modelo-padrao.md
          - Rich Picture: analise-de-requisitos/verificacao/richpicture-verificacao.md
          - Personas: analise-de-requisitos/verificacao/personas-verificacao.md
          - Storytelling: analise-de-requisitos/verificacao/storytelling-verificacao.md
          - Observação: analise-de-requisitos/verificacao/observacao-verificacao.md
          - Brainstorm: analise-de-requisitos/verificacao/brainstorming-verificacao.md
          - Léxicos: analise-de-requisitos/verificacao/lexicos-verificacao.md
          - Casos de Uso: analise-de-requisitos/verificacao/casos-de-uso-verificacao.md
          - In or Out: analise-de-requisitos/verificacao/inorout-verificacao.md
          - Cenarios: analise-de-requisitos/verificacao/cenarios-verificacao.md
          - Especificação Suplementar: analise-de-requisitos/verificacao/especificacao-suplementar.md
          - História de Usuários: analise-de-requisitos/verificacao/historia-usuario.md
          - Tree Level Scale: analise-de-requisitos/verificacao/treelevelscale-verificacao.md
          - Teste Piloto - Lichess:
              - Rich Picture: analise-de-requisitos/verificacao/testePiloto-Lichess/richpicture-Lichess.md
              - Personas: analise-de-requisitos/verificacao/testePiloto-Lichess/personas-Lichess.md
              - Storytelling: analise-de-requisitos/verificacao/testePiloto-Lichess/storytelling-Lichess.md
              - Entrevista: analise-de-requisitos/verificacao/testePiloto-Lichess/entrevista-Lichess.md
              - Brainstorm: analise-de-requisitos/verificacao/testePiloto-Lichess/brainstorm-Lichess.md
              - First Things First: analise-de-requisitos/verificacao/testePiloto-Lichess/Ftf-Lichess.md
              - Moscow: analise-de-requisitos/verificacao/testePiloto-Lichess/moscow-Lichess.md
              - Cenários: analise-de-requisitos/verificacao/testePiloto-Lichess/Cenarios-Lichess.md
              - Léxicos: analise-de-requisitos/verificacao/testePiloto-Lichess/lexicos-Lichess.md
              - Casos de Uso: analise-de-requisitos/verificacao/testePiloto-Lichess/casos-de-uso-Lichess.md
              - Especificação Suplementar: analise-de-requisitos/verificacao/testePiloto-Lichess/especificacao-suplementar.md
              - História de Usuário: analise-de-requisitos/verificacao/testePiloto-Lichess/historia-usuario.md
              - Backlog: analise-de-requisitos/verificacao/testePiloto-Lichess/backlogs-verificacao.md
              - NFR Framework: analise-de-requisitos/verificacao/testePiloto-Lichess/nfrFramework-verificacao.md
      - Validação:
          - Prototipagem: analise-de-requisitos/validacao/prototipacao.md
          - Comprovação Informal: analise-de-requisitos/validacao/comprovacao-informal.md
  - Pós-Rastreabilidade:
      - Backward-from: pos-rastreabilidade/backward-from.md
      - Forward-from: pos-rastreabilidade/forward-from.md
  - Apresentação Final: 
      - Técnicas utilizadas no projeto: entrega-final/tecnicas-projeto.md
      - Tabela de ferramentas: entrega-final/tabela-ferramentas.md
      - Tabela de artefatos: entrega-final/tabela-artefatos.md
      - Tabela de apresentações: entrega-final/tabela-apresentacoes.md
      - Tabela de verificação e validação: entrega-final/tabela-vericacao-validacao.md
      - Resultados Alcançados: entrega-final/resultados-alcancados.md
  - Atas das Reuniões:
      - Reunião 1 - 15/11/2022: atas-das-reunioes/reuniao1.md
      - Reunião 2 - 17/11/2022: atas-das-reunioes/reuniao2.md
      - Reunião 3 - 22/11/2022: atas-das-reunioes/reuniao3.md
      - Reunião 4 - 01/12/2022: atas-das-reunioes/reuniao4.md
  - Apresentações:
      - Etapa 1 - 21/11/2022: apresentacoes/etapa1.md
      - Etapa 2 - 30/11/2022: apresentacoes/etapa2.md
      - Etapa 3 - 12/12/2022: apresentacoes/etapa3.md
      - Etapa 4 - 04/01/2023: apresentacoes/etapa4.md
      - Etapa 5 - 09/01/2023: apresentacoes/etapa5.md
      - Etapa 6 - 16/01/2023: apresentacoes/etapa6.md
      - Etapa 7 - 23/01/2023: apresentacoes/etapa7.md
